"""Stage 2 regressions; all mutated/generated bytes here are synthetic test data."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

from scripts import vendor_rk as v

from .parity import rank_counts, run_parity
from .test_flop_parity import sample


@pytest.fixture(autouse=True)
def synthetic_lock_identity(monkeypatch: pytest.MonkeyPatch) -> None:
    from importlib.metadata import version

    lock = (
        "\n".join(
            f'[[package]]\nname = "{name}"\nversion = "{version(name)}"'
            for name in ("pydantic", "pydantic-core")
        )
        + "\n"
    ).encode()
    # Only synthetic test snapshots use this lock; real-snapshot tests use the pinned digest.
    monkeypatch.setattr(v, "PINNED_UV_LOCK_SHA256", v.digest(lock), raising=False)


def test_f2_default_cannot_claim_workload_parity() -> None:
    row = sample()
    result = run_parity([row], lambda *args: rank_counts(row))
    assert result["kind"] == "harness self-test (not workload parity)"


def synthetic_snapshot(root: Path) -> Path:
    """Complete matrix with sentinel values, never an actual workload oracle."""
    files: dict[str, bytes] = {}
    rows: list[dict[str, Any]] = []
    for component in v.REQUIRED_COMPONENTS:
        files[f"components/{component}"] = b"synthetic component\n"
    for n in range(3):
        model = {"id": f"synthetic-{n}", "model": {}, "shape": {}, "sources": ["synthetic"]}
        files[f"model_shapes/{model['id']}.json"] = v.canonical(model)
        for component in v.REQUIRED_COMPONENTS:
            for precision in v.component_precisions(component):
                for tp in (1, 8):
                    for query in v.QUERIES:
                        rows.append(
                            {
                                "id": str(len(rows)),
                                "model_id": model["id"],
                                "model": {},
                                "model_shape": {},
                                "model_sources": ["synthetic"],
                                "rk_sha": v.PIN,
                                "counts_scope": "replica",
                                "duration_scope": "one_tp_rank_no_collectives",
                                "duration_method": str(query["phase"]) + "_s",
                                "duration_s": 1.0,
                                "tp": tp,
                                "precision": precision,
                                "query": query,
                                "component_params_file": f"components/{component}",
                                "component_params_sha256": v.digest(b"synthetic component\n"),
                                "counts": {
                                    "matrix_ops": 8.0,
                                    "memory_read_bytes": 16.0,
                                    "memory_write_bytes": None
                                    if query["phase"] == "decode"
                                    else 8.0,
                                },
                            }
                        )
    files["parity/fixtures.json"] = v.canonical(rows)
    files["parity/refusals.json"] = v.canonical(
        [
            {
                "component_params_file": "components/asic_placeholder.yaml",
                "compute": p,
                "kv_cache": p,
                "exception": "UnsupportedPrecision",
                "message": "synthetic refusal",
            }
            for p in ("bf16", "fp8")
        ]
    )
    from importlib.metadata import version

    files["uv.lock"] = (
        "\n".join(
            f'[[package]]\nname = "{name}"\nversion = "{version(name)}"'
            for name in ("pydantic", "pydantic-core")
        )
        + "\n"
    ).encode()
    from importlib.metadata import version

    files["GENERATOR.json"] = v.canonical(
        {
            "script_sha256": v.digest(Path(v.__file__).read_bytes()),
            "oracle_program_sha256": v.digest(v.ORACLE_PROGRAM.encode()),
            "rk_sha": v.PIN,
            "counts_scope": "replica",
            "duration_scope": "one_tp_rank_no_collectives",
            "environment": {
                "python_version": "3.12.0",
                "implementation": "CPython",
                "uv_lock_sha256": v.digest(files["uv.lock"]),
                "packages": {
                    "pydantic": version("pydantic"),
                    "pydantic-core": version("pydantic-core"),
                },
            },
        }
    )
    v.publish_snapshot(root, v.snapshot_bytes(files, v.PIN))
    return root


def mutate_synthetic(root: Path, name: str, data: bytes) -> None:
    """Rehash synthetic corruption to distinguish integrity from compatibility."""
    target = root / name
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        target.chmod(0o644)
    target.write_bytes(data)
    manifest = root / "MANIFEST.json"
    inventory = json.loads(manifest.read_text())
    inventory["files"][name] = v.digest(data)
    manifest.chmod(0o644)
    manifest.write_bytes(v.canonical(inventory))


@pytest.mark.parametrize(
    "field,value",
    [
        ("rk_sha", "c" * 40),
        ("counts_scope", "per_rank"),
        ("oracle_program_sha256", "0" * 64),
        ("script_sha256", "0" * 64),
        ("extra", "unknown"),
    ],
)
def test_f3_metadata_tampering_is_not_manifest_integrity(
    tmp_path: Path,
    field: str,
    value: str,
) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    v.check_generator(root)
    metadata = json.loads((root / "GENERATOR.json").read_text())
    metadata[field] = value
    mutate_synthetic(root, "GENERATOR.json", v.canonical(metadata))
    v.check_manifest(root)  # attacker-rehashed bytes are internally consistent
    with pytest.raises(ValueError, match="GENERATOR|generator|oracle"):
        v.check_generator(root)


def test_f3_program_drift_fails_current_but_preserves_historical_identity(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    v.check_generator(root)
    monkeypatch.setattr(v, "ORACLE_PROGRAM", v.ORACLE_PROGRAM + "\n# drift\n")
    v.check_generator(root, current=False)
    with pytest.raises(ValueError, match="oracle"):
        v.check_generator(root)


def test_f4_absent_adr_requires_explicit_preparation(tmp_path: Path) -> None:
    adr = tmp_path / "U0001.md"
    with pytest.raises(ValueError, match="U0001.*missing"):
        v.check_adr_pin(adr, v.PIN)
    v.check_adr_pin(adr, v.PIN, pre_contract=True)
    adr.write_text(f"**Reference:** rk-sim `{'a' * 40}`\n")
    with pytest.raises(ValueError, match="upstream"):
        v.check_adr_pin(adr, v.PIN, pre_contract=True)


@pytest.mark.parametrize("state", ["missing", "renamed", "wrong_constant"])
def test_f4_strict_integration_binds_adr_and_contract(tmp_path: Path, state: str) -> None:
    adr = tmp_path / "docs/decisions/U0001-the-integration-contract.md"
    adr.parent.mkdir(parents=True)
    adr.write_text(f"**Reference:** rk-sim `{v.PIN}`\n")
    common = tmp_path / "contract/uarch_contract/common.py"
    common.parent.mkdir(parents=True)
    common.write_text(f'RK_SCHEMA_SNAPSHOT = "{v.PIN}"\n')
    v.check_contract_pin(tmp_path)
    if state == "missing":
        adr.unlink()
    elif state == "renamed":
        adr.rename(adr.with_name("renamed.md"))
    else:
        common.write_text(f'RK_SCHEMA_SNAPSHOT = "{"b" * 40}"\n')
    with pytest.raises(ValueError, match="U0001|RK_SCHEMA_SNAPSHOT"):
        v.check_contract_pin(tmp_path)


@pytest.mark.parametrize(
    "mutation", ["orphan_component", "orphan_model", "component_digest", "model_sources"]
)
def test_f5_inventory_must_match_matrix(tmp_path: Path, mutation: str) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    v.check_snapshot_inputs(root)
    if mutation == "orphan_component":
        mutate_synthetic(root, "components/npu-l4.yaml", b"synthetic additional component")
    elif mutation == "orphan_model":
        mutate_synthetic(root, "model_shapes/uncovered.json", v.canonical({"id": "uncovered"}))
    else:
        rows = json.loads((root / "parity/fixtures.json").read_text())
        rows[0][
            "component_params_sha256" if mutation == "component_digest" else "model_sources"
        ] = "0" * 64 if mutation == "component_digest" else ["wrong source"]
        mutate_synthetic(root, "parity/fixtures.json", v.canonical(rows))
    v.check_manifest(root)
    with pytest.raises(ValueError, match="matrix|model|component|sidecar"):
        v.check_snapshot_inputs(root)


@pytest.mark.parametrize("flag", ["--skip-worktree", "--assume-unchanged", "ignored"])
def test_f6_real_index_flags_and_ignored_shadow_refused(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    flag: str,
) -> None:
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    (tmp_path / "tracked.py").write_text("ORIGINAL = 1\n")
    subprocess.run(["git", "-C", str(tmp_path), "add", "tracked.py"], check=True)
    if flag == "ignored":
        (tmp_path / ".git/info/exclude").write_text("shadow.py\n")
        (tmp_path / "shadow.py").write_text("import os\n")
    else:
        subprocess.run(["git", "-C", str(tmp_path), "update-index", flag, "tracked.py"], check=True)
        (tmp_path / "tracked.py").write_text("MODIFIED = 2\n")
    real_git = v.git

    def repo_git(root: Path, *args: str) -> str:
        # No synthetic commit is needed. Simulate a clean HEAD/status; inspect the real index.
        if args == ("rev-parse", "HEAD"):
            return v.PIN
        if args[0] == "status":
            return ""
        return real_git(root, *args)

    monkeypatch.setattr(v, "git", repo_git)
    with pytest.raises(ValueError, match="flags|ignored"):
        v.check_clone(tmp_path, v.PIN)


def test_f7_environment_metadata_is_required_for_current_compatibility(tmp_path: Path) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    metadata = json.loads((root / "GENERATOR.json").read_text())
    del metadata["environment"]
    mutate_synthetic(root, "GENERATOR.json", v.canonical(metadata))
    v.check_generator(root, current=False)  # legacy identity, not current approval
    with pytest.raises(ValueError, match="environment"):
        v.check_generator(root)


def test_f7_locked_environment_is_checked_before_execution(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls = []

    def refuse(command: list[str], **kwargs: Any) -> Any:
        calls.append(command)
        assert command[:2] == ["uv", "sync"]
        assert {"--check", "--locked", "--offline"} <= set(command)
        raise subprocess.CalledProcessError(1, command, stderr="would change dependencies")

    monkeypatch.setattr(subprocess, "run", refuse)
    with pytest.raises(ValueError, match="environment"):
        v.verify_oracle_environment(tmp_path, {})
    assert len(calls) == 1


@pytest.mark.parametrize("where", ["root", "parent"])
def test_f10_symlink_root_or_vendor_ancestor_refused(tmp_path: Path, where: str) -> None:
    original = tmp_path / "real/snapshot"
    v.publish_snapshot(original, v.snapshot_bytes({"schema.json": b"{}"}, v.PIN))
    link = tmp_path / "link"
    link.symlink_to(original if where == "root" else original.parent, target_is_directory=True)
    with pytest.raises(ValueError, match="symlink"):
        v.check_manifest(link if where == "root" else link / "snapshot")


def test_f11_publish_reports_created_and_verified(tmp_path: Path) -> None:
    data = v.snapshot_bytes({"synthetic.json": b"{}"}, v.PIN)
    root = tmp_path / "snapshot"
    assert v.publish_snapshot(root, data) == "created"
    assert v.publish_snapshot(root, data) == "verified-identical"
    with pytest.raises(ValueError, match="different"):
        v.publish_snapshot(root, v.snapshot_bytes({"synthetic.json": b"[]"}, v.PIN))


def test_f11_check_does_not_claim_publication(monkeypatch: pytest.MonkeyPatch, capsys: Any) -> None:
    # Pure CLI test: verifier is tested separately; never run human generation.
    for name in (
        "check_adr_pin",
        "check_contract_pin",
        "check_manifest",
        "check_generator",
        "check_snapshot_inputs",
    ):
        if hasattr(v, name):
            monkeypatch.setattr(v, name, lambda *args, **kwargs: None)
    monkeypatch.setattr(sys, "argv", ["vendor_rk.py", "--check"])
    v.main()
    assert "committed" not in capsys.readouterr().out


def test_f12_ci_typechecks_b_deliverables() -> None:
    import tomllib

    config = tomllib.loads((v.ROOT / "pyproject.toml").read_text())
    workflow = (v.ROOT / ".github/workflows/ci.yml").read_text()
    assert "uv run mypy src contract scripts" in workflow or {"src", "contract", "scripts"} <= set(
        config["tool"]["mypy"]["files"]
    )


def test_f15_vendor_readme_documents_layout_and_lifecycle() -> None:
    text = (v.ROOT / "contract/vendor/README.md").read_text()
    for entry in (
        "GENERATOR.json",
        "MANIFEST.json",
        "schema.json",
        "components/",
        "model_shapes/",
        "parity/fixtures.json",
        "parity/refusals.json",
        "rk/",
        "uv.lock",
    ):
        assert entry in text, entry
    assert "adopt" in text.lower() and "Never edit" in text


def test_f1_stacking_is_capped_per_fixture_channel() -> None:
    from .parity import Deviation, compare_counts

    deviations = [Deviation(str(i), "matrix_ops", 0.05, "synthetic term") for i in range(20)]
    with pytest.raises(ValueError, match="absolute.*5%"):
        compare_counts("stacked", {"matrix_ops": 200.0}, {"matrix_ops": 100.0}, deviations)


@pytest.mark.parametrize(
    "value,reference,adjustments",
    [
        (100.0, 100.0, [0.049]),
        (100.4, 100.0, [0.045]),
        (None, None, [0.01]),
        (0.0, 0.0, [0.01]),
        (100.0, 100.0, [0.05, -0.05]),
    ],
)
def test_f1_unnecessary_null_zero_and_cancelling_adjustments_refused(
    value: float | None,
    reference: float | None,
    adjustments: list[float],
) -> None:
    from .parity import Deviation, compare_counts

    ds = [Deviation(str(i), "matrix_ops", d, "synthetic term") for i, d in enumerate(adjustments)]
    with pytest.raises(ValueError):
        compare_counts("unneeded", {"matrix_ops": value}, {"matrix_ops": reference}, ds)


def test_f1_boundaries_and_four_reported_quantities() -> None:
    import math

    from .parity import Deviation, compare_counts

    ds = [
        Deviation("a", "matrix_ops", 0.03, "term a"),
        Deviation("b", "matrix_ops", 0.02, "term b"),
    ]
    assert compare_counts("boundary", {"matrix_ops": 105.5}, {"matrix_ops": 100.0}, ds) == 0.055
    with pytest.raises(AssertionError):
        compare_counts(
            "outside", {"matrix_ops": math.nextafter(105.5, math.inf)}, {"matrix_ops": 100.0}, ds
        )
    with pytest.raises(ValueError):
        compare_counts(
            "overbudget",
            {"matrix_ops": 105.0},
            {"matrix_ops": 100.0},
            [*ds, Deviation("c", "matrix_ops", 1e-9, "over budget")],
        )
    row = sample()
    counts = rank_counts(row) | {"matrix_ops": 105.5}
    report = run_parity([row], lambda *args: counts, deviations={row["id"]: ds})
    result = report["comparisons"][row["id"]]["matrix_ops"]
    assert result["raw_rel"] == 0.055
    assert result["signed_adjustment_rel"] == 0.05
    assert result["absolute_adjustment_rel"] == 0.05
    assert result["residual_rel"] == pytest.approx(0.005)
    # Opposing legitimate terms spend absolute budget, not just the net adjustment.
    cancelling = [
        Deviation("a", "matrix_ops", 0.03, "addition"),
        Deviation("b", "matrix_ops", -0.02, "omission"),
    ]
    compare_counts("bounded cancellation", {"matrix_ops": 101.0}, {"matrix_ops": 100.0}, cancelling)


@pytest.mark.parametrize(
    "source",
    [
        "import importlib\nimportlib.import_module('r' + 'k')\n",
        "exec(open('contract/vendor/rk-sim@pin/rk/provenance.py').read())\n",
        "from scripts.vendor_rk import PIN\n",
        "from importlib import import_module as load\nload('rk')\n",
        "__import__('rk')\n",
    ],
)
def test_f13_dynamic_vendor_access_and_tool_imports_are_refused(
    tmp_path: Path, source: str
) -> None:
    from . import vendor_support

    root = tmp_path / "src/rkuarch"
    root.mkdir(parents=True)
    (root / "__init__.py").write_text(source)
    with pytest.raises(ValueError, match="isolation"):
        vendor_support.check_production_isolation(tmp_path)


def test_production_isolation() -> None:
    from . import vendor_support

    vendor_support.check_production_isolation(v.ROOT)


@pytest.mark.parametrize("mode", [0o444, 0o644])
def test_f14_modes_do_not_replace_integrity_checks(tmp_path: Path, mode: int) -> None:
    root = tmp_path / "snapshot"
    v.publish_snapshot(root, v.snapshot_bytes({"synthetic.json": b"{}"}, v.PIN))
    for path in root.iterdir():
        path.chmod(mode)
    v.check_manifest(root)
    leaf = root / "synthetic.json"
    leaf.chmod(0o644)
    leaf.write_bytes(b"[]")
    leaf.chmod(mode)
    with pytest.raises(ValueError, match="MANIFEST mismatch"):
        v.check_manifest(root)


def test_f14_docs_explain_checkout_modes() -> None:
    prompt = (v.ROOT / "docs/prompts/U-P2-vendored-snapshot-and-parity.md").read_text()
    assert "local precaution" in prompt and "0644" in prompt


def test_f9_nominal_parameter_offsets_are_recorded_without_correction(
    lane_a: dict[str, Any],
) -> None:
    record = json.loads((v.ROOT / "docs/reviews/U1-U-P2-nominal-parameters.json").read_text())
    assert record["denominator"] == "shape_implied"
    assert record["difference"] == "nominal_minus_shape_implied"
    assert record["automatic_adjustment"] is False
    model_shape = lane_a["model_shape"]
    for entry in record["models"]:
        sidecar = json.loads(
            (v.ROOT / "contract/fixtures/model_shapes" / (entry["id"] + ".json")).read_text()
        )
        model = model_shape.ModelSpec.model_validate(sidecar["model"])
        shape = model_shape.ModelShape.model_validate(sidecar["shape"])
        model_shape.check_parity(model, shape)  # existing rule, no new threshold
        implied = model_shape.implied_params(model, shape)
        for i, name in enumerate(("total_params", "active_params")):
            values = entry[name]
            assert values["nominal"] == getattr(model, name)
            assert values["shape_implied"] == implied[i]
            assert values["signed_difference"] == values["nominal"] - implied[i]
            assert values["relative_difference"] == values["signed_difference"] / implied[i]


@pytest.mark.parametrize("mutation", ["missing", "version", "lock", "packages"])
def test_f7_environment_tampering_is_refused(tmp_path: Path, mutation: str) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    data = json.loads((root / "GENERATOR.json").read_text())
    env = data["environment"]
    if mutation == "missing":
        del env["python_version"]
    elif mutation == "version":
        env["python_version"] = "unknown"
    elif mutation == "lock":
        env["uv_lock_sha256"] = "0" * 64
    else:
        env["packages"]["pydantic"] = "0.0.0"
    mutate_synthetic(root, "GENERATOR.json", v.canonical(data))
    v.check_manifest(root)
    with pytest.raises(ValueError, match="environment"):
        v.check_generator(root)


def test_f7_ci_runtime_need_not_equal_oracle_runtime(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = synthetic_snapshot(tmp_path / "snapshot")
    data = json.loads((root / "GENERATOR.json").read_text())
    lock = (
        b'[[package]]\nname="pydantic"\nversion="2.12.0"\n'
        b'[[package]]\nname="pydantic-core"\nversion="2.41.1"\n'
    )
    data["environment"]["packages"] = {"pydantic": "2.12.0", "pydantic-core": "2.41.1"}
    data["environment"]["uv_lock_sha256"] = v.digest(lock)
    monkeypatch.setattr(v, "PINNED_UV_LOCK_SHA256", v.digest(lock))
    mutate_synthetic(root, "uv.lock", lock)
    mutate_synthetic(root, "GENERATOR.json", v.canonical(data))
    v.check_generator(root)  # recorded lock-consistent runtime, independent of this process


def test_f1_zero_reference_has_no_relative_denominator() -> None:
    row = sample() | {"counts": {"matrix_ops": 0.0}}
    report = run_parity([row], lambda *args: {"matrix_ops": 0.0})
    assert report["comparisons"][row["id"]]["matrix_ops"] == {
        "actual": 0.0,
        "reference": 0.0,
        "unit": "op",
        "reference_state": "zero",
        "raw_rel": None,
        "signed_adjustment_rel": 0.0,
        "absolute_adjustment_rel": 0.0,
        "residual_rel": None,
    }
    with pytest.raises(AssertionError, match="nonzero against zero"):
        run_parity([row], lambda *args: {"matrix_ops": 1.0})


def test_f1_negative_boundary_and_unadjusted_boundary() -> None:
    import math

    from .parity import Deviation, compare_counts

    ds = [Deviation("minus", "matrix_ops", -0.05, "omitted operator")]
    assert compare_counts("negative", {"matrix_ops": 94.5}, {"matrix_ops": 100.0}, ds) == 0.055
    with pytest.raises(AssertionError):
        compare_counts(
            "outside", {"matrix_ops": math.nextafter(94.5, 0.0)}, {"matrix_ops": 100.0}, ds
        )
    assert compare_counts("raw", {"matrix_ops": 100.5}, {"matrix_ops": 100.0}) == 0.005
    with pytest.raises(AssertionError):
        compare_counts(
            "raw outside", {"matrix_ops": math.nextafter(100.5, 200.0)}, {"matrix_ops": 100.0}
        )
